[771] Allow the drop of elements on empty diagram nodes
eclipse-syson/syson pull request #772
Opened 2024-10-04 14:52 UTC by gdaniel

Bug: https://github.com/eclipse-syson/syson/issues/771

# Pull request template

PLEASE READ ALL ITEMS AND CHECK RELEVANT CHECKBOXES BELOW.

## Project management

- [x] Has the pull request been added to the relevant project and milestone?
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [x] Have the relevant labels been added to the issues? (`area:`, `type:`)
- [x] Have the relevant issues been added to the same project and milestone as the pull request?

## Changelog and release notes

- [x] Has the `CHANGELOG.adoc` + `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc` been updated to reference the relevant issues?
- [x] Have the relevant API breaks been described in the `CHANGELOG.adoc` + `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?
- [x] In case of a change with a visual impact, are there any screenshots in the `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?
- [x] In case of a key change, has the change been added to `Key highlights` section in `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?
- [x] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc` + `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc`?

## Documentation

- [x] Have you included an update of the [documentation](https://doc.mbse-syson.org) in your pull request? Please ask yourself if an update (installation manual, user manual, developer manual...) is needed and add one accordingly.

## Tests

- [ ] Is the code properly tested? Any pull request (fix, enhancement or new feature) should come with a test (or several). It could be unit tests, integration tests or cypress tests depending on the context. Only doc and releng pull request do not need for tests.

2024-10-04 14:53 UTC, gdaniel commented on backend/views/syson-diagram-actionflow-view/src/test/java/org/eclipse/syson/diagram/actionflow/view/ActionFlowViewDiagramDescriptionTests.java
> +        new DiagramDescriptionHasOneEmptyDiagramNodeChecker().check(this.diagramDescription);
Added some tests to check that diagrams that should have an empty diagram node have one, and diagrams that shouldn't don't

2024-10-04 14:54 UTC, gdaniel commented
This PR is a draft: it requires additional integration tests on the backend to properly test the drag & drop on empty diagram nodes.

2024-10-07 12:59 UTC, gdaniel commented on backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVEdgeCreationTests.java
> +    private SemanticRunnableFactory semanticRunnableFactory;
I renamed the `SemanticCheckerFactory` to `SemanticRunnableFactory` since it can be used to create any kind of runnable (not only checkers)

2024-10-07 13:13 UTC, AxelRICHARD requested changes

2024-10-07 13:17 UTC, gdaniel commented on CHANGELOG.adoc
> +The class `SemanticCheckerFactory` to `SemanticRunnableFactory` to reflect the new use cases of the class.
fixed

2024-10-07 13:17 UTC, gdaniel commented on doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
> +The class `SemanticCheckerFactory` to `SemanticRunnableFactory` to reflect the new use cases of the class.
fixed

2024-10-07 14:33 UTC, AxelRICHARD approved these changes

2024-10-07 14:34 UTC, merged